Implement coerce option for Class Attributes
dry-rb/dry-core pull request #43
Opened 2020-11-15 13:33 UTC by tallica

Added a `coerce` option to Class Attributes instead of introducing breaking changes for the `type` option (related: https://github.com/dry-rb/dry-core/pull/42)

2020-11-16 11:26 UTC, solnic commented
@tallica could you address codacy feedback except `Perceived complexity for defines is too high. [8/7]`? (just disable that cop in the marked method)

2020-11-16 14:01 UTC, flash-gordon requested changes

2020-11-17 21:46 UTC, tallica commented on lib/dry/core/class_attributes.rb
> +                  raise InvalidCoerceOption.new(name) unless coerce.respond_to?(:call)
Good point! Updated :)

2020-11-18 08:05 UTC, flash-gordon approved these changes
looks good! I'll merge it later today

2020-11-18 21:27 UTC, merged

2020-11-18 21:37 UTC, flash-gordon commented
Ugh, I hit the button before I realized I should have squashed commits. Anyway, I'll cut a release tomorrow